---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$(whoami)/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache $DEPLOYPATH/public/uploads 2>/dev/null || true
